"use client";

import { BookOpenCheck, CircleCheck, Eye, FilePlus2, FileUp, GitBranch, Plus, Rocket, Save, Search, Trash2, WandSparkles } from "lucide-react";
import { useEffect, useState } from "react";
import type { PagedScenariosContract, ProblemDetailsContract, PublishedExperienceContract, ScenarioContract, ScenarioPreviewContract, ScenarioVersionContract, StructureReportContract, ValidationReportContract } from "@/shared/api/contracts";
import { gameCopy } from "@/shared/lib/game-copy";

type Report = { kind: "validation"; value: ValidationReportContract } | { kind: "analysis"; value: StructureReportContract } | { kind: "preview"; value: ScenarioPreviewContract } | { kind: "published"; value: ScenarioVersionContract };
interface DraftChoice { id: string; text: string; targetNodeId: string; condition?: unknown; effects: unknown[] }
interface DraftNode { id: string; text: string; isEnding?: boolean; choices: DraftChoice[]; [key: string]: unknown }
interface NarrativeDraft { schemaVersion: number; title: string; initialNodeId: string; nodes: DraftNode[]; [key: string]: unknown }

export function StudioWorkbench() {
  const [source, setSource] = useState("");
  const [userName, setUserName] = useState("");
  const [password, setPassword] = useState("");
  const [authenticated, setAuthenticated] = useState(false);
  const [scenario, setScenario] = useState<ScenarioContract>();
  const [scenarios, setScenarios] = useState<ScenarioContract[]>([]);
  const [scenarioQuery, setScenarioQuery] = useState("");
  const [selectedNodeId, setSelectedNodeId] = useState("");
  const [report, setReport] = useState<Report>();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string>();
  const [experience, setExperience] = useState<PublishedExperienceContract>();
  const [categoryId, setCategoryId] = useState("");
  const [generationPrompt, setGenerationPrompt] = useState("");
  const [provider, setProvider] = useState("offline");
  const [targetMinutes, setTargetMinutes] = useState("15");
  const [tone, setTone] = useState("immersive");

  useEffect(() => { void fetch("/api/experience").then((response) => read<PublishedExperienceContract>(response)).then((value) => { setExperience(value); setCategoryId(value.document.categories.find((category) => category.isVisible)?.id ?? ""); if (value.document.aiProviders.some((item) => item.type === "AzureAiFoundry" && item.enabled)) setProvider("azureAiFoundry"); }).catch(() => undefined); }, []);

  async function loadScenarios(query = scenarioQuery) { const page = await read<PagedScenariosContract>(await fetch(`/api/scenarios?query=${encodeURIComponent(query)}`)); setScenarios(page.items); }
  function openScenario(item: ScenarioContract) { const document = narrativeDraft(item.draftJson); setScenario(item); setSource(formatDraft(item.draftJson)); setSelectedNodeId(document.initialNodeId); setReport(undefined); }
  async function authenticate() { await run(async () => { await read<{ expiresAt: string }>(await fetch("/api/auth", jsonRequest({ mode: "login", userName, password }))); setPassword(""); setAuthenticated(true); await loadScenarios(); }); }
  async function importScenario() { await run(async () => { const document = parse(source); const imported = await read<ScenarioContract>(await fetch("/api/scenarios", jsonRequest({ document }))); openScenario(imported); await loadScenarios(); }); }
  async function updateDraft() { if (!scenario) return; await run(async () => { const updated = await read<ScenarioContract>(await fetch(`/api/scenarios/${scenario.id}`, { ...jsonRequest({ expectedRevision: scenario.revision, document: parse(source) }), method: "PUT" })); openScenario(updated); await loadScenarios(); }); }
  async function generateScenario() { await run(async () => { const generated = await read<ScenarioContract>(await fetch("/api/studio/generate", jsonRequest({ categoryId, prompt: generationPrompt, provider, targetMinutes: Number(targetMinutes), tone }))); openScenario(generated); await loadScenarios(); }); }
  async function action(kind: "validate" | "analyze" | "preview" | "publish") { if (!scenario) return; await run(async () => { const draft = narrativeDraft(source); const payload = kind === "preview" ? { action: kind, preview: { nodeId: selectedNodeId || draft.initialNodeId, turn: 0, variables: {}, characteristics: {}, inventory: [], evidence: [], relations: {}, rewards: [], visitedNodes: [] } } : { action: kind, expectedRevision: scenario.revision }; const response = await fetch(`/api/scenarios/${scenario.id}`, jsonRequest(payload)); if (kind === "validate") setReport({ kind: "validation", value: await read<ValidationReportContract>(response) }); else if (kind === "analyze") setReport({ kind: "analysis", value: await read<StructureReportContract>(response) }); else if (kind === "preview") setReport({ kind: "preview", value: await read<ScenarioPreviewContract>(response) }); else setReport({ kind: "published", value: await read<ScenarioVersionContract>(response) }); }); }
  async function archiveScenario() { if (!scenario || !window.confirm(`Archiver ${scenario.title} ?`)) return; await run(async () => { const response = await fetch(`/api/scenarios/${scenario.id}?expectedRevision=${scenario.revision}`, { method: "DELETE" }); if (!response.ok) await read<void>(response); setScenario(undefined); setSource(""); setSelectedNodeId(""); await loadScenarios(); }); }
  async function run(operation: () => Promise<void>) { setBusy(true); setError(undefined); try { await operation(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Erreur inattendue"); } finally { setBusy(false); } }

  const copy = (key: string, fallback: string) => gameCopy(experience?.document, key, fallback);
  const draft = narrativeDraft(source);
  const selectedNode = draft.nodes.find((node) => node.id === selectedNodeId);
  function updateNode(mutator: (node: DraftNode) => DraftNode) { setSource(JSON.stringify({ ...draft, nodes: draft.nodes.map((node) => node.id === selectedNodeId ? mutator(node) : node) }, null, 2)); }

  return <>
    {error && <p className="studio-error" role="alert">{error}</p>}
    <details className="studio-auth"><summary>{authenticated ? `Compte auteur connecté · ${userName}` : "Connecter un compte auteur"}</summary><div><label>Identifiant<input autoComplete="username" value={userName} onChange={(event) => setUserName(event.target.value)} /></label><label>Mot de passe<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="button button--quiet" type="button" disabled={busy || !userName || !password} onClick={authenticate}>Se connecter</button><a className="button microsoft-button" href="/api/auth/entra/start"><span>▦</span> Continuer avec Microsoft</a></div></details>
    <section className="generation-canvas"><div className="generation-intro"><span><WandSparkles /></span><div><p className="eyebrow">{copy("studio.copilot.eyebrow", "Copilote narratif")}</p><h2>{copy("studio.copilot.title", "Du monde global au premier brouillon")}</h2><p>{copy("studio.copilot.subtitle", "Le moteur combine l’histoire globale, la catégorie et votre intention.")} <strong>{experience?.document.game.name}</strong></p></div></div><div className="generation-form"><label>{copy("studio.category.label", "Catégorie")}<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}>{experience?.document.categories.filter((category) => category.isVisible).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>{copy("studio.provider.label", "Provider")}<select value={provider} onChange={(event) => setProvider(event.target.value)}><option value="offline">Hors ligne déterministe</option>{experience?.document.aiProviders.some((item) => item.type === "AzureAiFoundry" && item.enabled) && <option value="azureAiFoundry">Azure AI Foundry</option>}</select></label><label>{copy("studio.duration.label", "Durée cible")}<input type="number" min="3" max="90" value={targetMinutes} onChange={(event) => setTargetMinutes(event.target.value)} /></label><label>{copy("studio.tone.label", "Ton")}<input value={tone} onChange={(event) => setTone(event.target.value)} /></label><label className="prompt-field">{copy("studio.prompt.label", "Votre intention")}<textarea value={generationPrompt} onChange={(event) => setGenerationPrompt(event.target.value)} placeholder="Une enquête en plusieurs scènes, avec indices, dilemmes et trois fins distinctes…" /></label><button className="button button--primary generation-submit" disabled={busy || !authenticated || generationPrompt.trim().length < 20 || !categoryId} onClick={generateScenario}><WandSparkles /> Générer le brouillon</button></div></section>
    <section className="studio-workspace" aria-label="Studio low-code">
      <aside className="studio-library"><div className="studio-library-heading"><div><p className="eyebrow">Vos scénarios</p><strong>{scenarios.length} brouillons</strong></div><FilePlus2 /></div><label className="studio-search"><Search /><input value={scenarioQuery} onChange={(event) => setScenarioQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void loadScenarios(); }} placeholder="Titre ou intention…" /></label>{scenarios.map((item) => <button key={item.id} className={scenario?.id === item.id ? "scenario-row is-active" : "scenario-row"} onClick={() => openScenario(item)}><strong>{item.title}</strong><small>r{item.revision} · {item.categoryId ? experience?.document.categories.find((category) => category.id === item.categoryId)?.name : "Sans catégorie"}</small></button>)}</aside>
      <div className="story-graph-panel"><div className="studio-toolbar"><div><p className="eyebrow">Arborescence narrative</p><strong>{scenario ? `${scenario.title} · révision ${scenario.revision}` : draft.title || "Nouveau brouillon"}</strong></div><div>{scenario && <button type="button" className="button button--quiet" disabled={busy} onClick={updateDraft}><Save size={16} /> Enregistrer</button>}<button type="button" className="button button--primary" disabled={busy || !source.trim()} onClick={importScenario}><FileUp size={16} /> Importer une copie</button></div></div>{draft.nodes.length ? <div className="story-graph">{draft.nodes.map((node, index) => <button key={node.id} className={`graph-node ${selectedNodeId === node.id ? "is-selected" : ""} ${node.isEnding ? "is-ending" : ""}`} onClick={() => setSelectedNodeId(node.id)}><span>{index + 1}</span><div><small>{node.id}{node.id === draft.initialNodeId ? " · départ" : node.isEnding ? " · fin" : ""}</small><strong>{node.text || "Scène sans texte"}</strong>{node.choices.map((choice) => <em key={choice.id}>{choice.text} <b>→ {choice.targetNodeId}</b></em>)}</div></button>)}</div> : <div className="graph-empty"><GitBranch /><h3>Générez ou importez un scénario</h3><p>Les scènes, choix et destinations formeront ici une arborescence visuelle.</p></div>}</div>
      <aside className="node-inspector"><p className="eyebrow">Inspecteur low-code</p>{selectedNode ? <><label>ID de scène<input value={selectedNode.id} disabled /></label><label>Texte de la scène<textarea value={selectedNode.text} onChange={(event) => updateNode((node) => ({ ...node, text: event.target.value }))} /></label><label className="check-line"><input type="checkbox" checked={Boolean(selectedNode.isEnding)} onChange={(event) => updateNode((node) => ({ ...node, isEnding: event.target.checked }))} /> Fin de l’histoire</label><h3>Choix</h3>{selectedNode.choices.map((choice, index) => <div className="choice-editor" key={choice.id}><input aria-label="Libellé du choix" value={choice.text} onChange={(event) => updateNode((node) => ({ ...node, choices: node.choices.map((item, itemIndex) => itemIndex === index ? { ...item, text: event.target.value } : item) }))} /><select aria-label="Destination" value={choice.targetNodeId} onChange={(event) => updateNode((node) => ({ ...node, choices: node.choices.map((item, itemIndex) => itemIndex === index ? { ...item, targetNodeId: event.target.value } : item) }))}>{draft.nodes.map((target) => <option key={target.id}>{target.id}</option>)}</select><button aria-label="Supprimer le choix" onClick={() => updateNode((node) => ({ ...node, choices: node.choices.filter((_, itemIndex) => itemIndex !== index) }))}><Trash2 /></button></div>)}<button className="button button--quiet" onClick={() => updateNode((node) => ({ ...node, choices: [...node.choices, { id: `choice-${node.choices.length + 1}`, text: "Nouveau choix", targetNodeId: draft.nodes.find((item) => item.id !== node.id)?.id ?? node.id, condition: null, effects: [] }] }))}><Plus /> Ajouter un choix</button></> : <p>Sélectionnez une scène.</p>}<details className="advanced-source"><summary>Source JSON avancée</summary><textarea aria-label="Document de scénario JSON" spellCheck={false} value={source} onChange={(event) => setSource(event.target.value)} /></details><div className="studio-engine-actions"><button disabled={!scenario || busy} onClick={() => action("validate")}><BookOpenCheck /> Valider</button><button disabled={!scenario || busy} onClick={() => action("analyze")}><GitBranch /> Analyser</button><button disabled={!scenario || busy} onClick={() => action("preview")}><Eye /> Prévisualiser</button><button className="publish-action" disabled={!scenario || busy} onClick={() => action("publish")}><Rocket /> Publier</button>{scenario && <button className="danger-action" onClick={archiveScenario}><Trash2 /> Archiver</button>}</div></aside>
    </section>
    {report && <ReportView report={report} />}
  </>;
}

function ReportView({ report }: { report: Report }) { if (report.kind === "validation") return <section className="studio-report"><h2><CircleCheck /> Validation {report.value.isValid ? "réussie" : "à corriger"}</h2>{report.value.issues.length === 0 ? <p>Aucun problème détecté.</p> : <ul>{report.value.issues.map((issue, index) => <li key={`${issue.path}-${issue.code}-${index}`}><strong>{issue.code}</strong> · {issue.path}<br />{issue.message}</li>)}</ul>}</section>; if (report.kind === "analysis") return <section className="studio-report"><h2><GitBranch /> Analyse structurelle</h2><div className="report-metrics"><span><b>{report.value.loops.length}</b> boucles</span><span><b>{report.value.conditionalDeadEnds.length}</b> impasses</span><span><b>{report.value.unreachableEndingNodeIds.length}</b> fins inatteignables</span><span><b>{report.value.nodesWithoutEndingPath.length}</b> scènes sans fin</span></div></section>; if (report.kind === "preview") return <section className="studio-report preview-report"><h2><Eye /> Prévisualisation</h2><blockquote>{report.value.currentStep.text}</blockquote>{report.value.currentStep.choices.map((choice) => <span key={choice.id}>{choice.text}</span>)}</section>; return <section className="studio-report"><h2><Rocket /> Version {report.value.number} publiée</h2><small>Hash immuable : {report.value.snapshotHash}</small></section>; }
function narrativeDraft(value: string): NarrativeDraft { try { const parsed = JSON.parse(value) as Partial<NarrativeDraft>; return { ...parsed, schemaVersion: parsed.schemaVersion ?? 2, title: parsed.title ?? "", initialNodeId: parsed.initialNodeId ?? "", nodes: Array.isArray(parsed.nodes) ? parsed.nodes.map((node) => ({ ...node, id: node.id ?? "", text: node.text ?? "", choices: Array.isArray(node.choices) ? node.choices : [] })) : [] }; } catch { return { schemaVersion: 2, title: "", initialNodeId: "", nodes: [] }; } }
function jsonRequest(body: unknown): RequestInit { return { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }; }
function parse(value: string): Record<string, unknown> { try { return JSON.parse(value) as Record<string, unknown>; } catch { throw new Error("Le JSON n’est pas valide."); } }
function formatDraft(value: string) { try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; } }
async function read<T>(response: Response): Promise<T> { if (!response.ok) { const problem = await response.json().catch(() => undefined) as ProblemDetailsContract | undefined; throw new Error(problem?.detail ?? problem?.title ?? `Le service a répondu ${response.status}.`); } return response.status === 204 ? undefined as T : response.json() as Promise<T>; }
